apiVersion: v1
kind: PersistentVolume
metadata:
  name: wikidb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/raid/k8store/wiki/db"
